### ISSUE TITLE
MIPS generation - stack frame

### ISSUE THREAD

**Issue by Cathy-DYX** [LangProc/langproc-2021-cw#1]
Hello, I have a few questions regarding the call stack. I am mainly confused about how we can determine the frame size. From what I found out, the stack frame contains: $ra, $fp, preserved registers, padding, local data, $gp, arguments for called functions. 
I am not sure how preserved registers are used. From what I observed from the mips code, the number of preserved registers changes depending on the operations within the function. However, I'm not sure how we can determine the number of preserved registers we need when performing different operations.
What is the safe way to allocate frame size?
Is this (using stack) the method that we are supposed to use? We are really confused about this part and there are also some other behaviours of the frame size that we couldn't understand. Would it be possible to have a quick Teams call? We would be very grateful.
Thank you!

**Comment by ymherklotz** [comment]
Yes, that seems to all be correct.  In mips, each register has a purpose, which is defined by the [ABI](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf), which should explain all the necessary conventions that need to be maintained, and also has good examples.  For example, [it defines the purpose of registers](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf#page=24), so

- `$v` registers are used to pass back return values,
- `$a` registers are used for passing arguments,
- `$t` registers are used for temporary calculations (not preserved),
- `$s` registers are saved, meaning they need to be restored at the end of the function call.

So, you only need to preserve `$s` registers, which could be done, for example, by copying over all the registers into the stack everytime you do a function call.  Or, you could also just ensure your code never modifies them, in which case they don't need to be saved.

The ABI also has a great explanation of what the [stack frame consist of](math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf#page=27).

It also describes how [arguments should be passed](math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf#page=29), and using the information you have about the types of the function arguments, you should be able to write the correct code to either load the arguments from the stack, or just take them from the `$a` registers (which is sufficient for <4 int arguments).

Finally, local data is probably the hardest to allocate for.  There are two possible ways to handle this though, either you can estimate up front how much total stack space you'll need by analysing your function contents, or you could take a more dynamic approach, and increase the stack pointer as you go (I think most compilers would do the first).

I hope this helps, but if you still want to jump on a call with someone, it might be quicker to send a message on teams in the Questions channel, as a TA might be free.

**Comment by Cathy-DYX** [comment]
Thank you so much for your explanation! I'll read through the document.
I have another question about representing 'double' in mips. I got the following mips code when defining a double variable. 
![image](https://user-images.githubusercontent.com/62194910/156077500-ecd8b10c-2e45-47fa-813a-8ee436ea1d22.png)
I'm not really sure how these long numbers represent 1 and 3.2 in double.

**Comment by Aeroking21** [comment]
Hi @ymherklotz sorry for barging in to this issue, but this is the first I am hearing about frame size and call stack, I must've missed it in the lectures, by any chance do you know in which lectures this is covered?

**Comment by ymherklotz** [comment]
### About doubles

So I wouldn't worry too much about doubles at the start of the compiler, as there is enough to do with only `int`.

But to explain the 1 (which may help you deduce 3.2): (following [this guide](https://www.ece.unb.ca/tervo/ee6373/IEEE64.htm)

first, lets convert the decimal values(1074370969, -1717986918) to a binary 64 bit value: 

`01000000000010011001100110011001 10011001100110011001100110011010`

Then, floating point says that it's composed of:
- 1 bit for sign
- 11 bits for the exponent *p* (- `0x3ff` offset)
- 52 bits for the mantissa *m* (with an implied 1 at the start of it).

Then, we can calculate the number by doing *m* * 2^*p*.

So, sign bit is 0, mantissa is `10000000000 - 011111111111 = 00000000001 = 1` and finally 

`10011001100110011001 10011001100110011001100110011010 = 1+1/2+1/16+1/32+1/256+1/512... ~= 1.599609375`

So:

`2^1 * 1.599609375 = 3.19921875 ~= 3.2`

This would have more precision if you actually calculate the whole mantissa.

### About the lecture on functions

I see that Lecture 10 discusses function stack and calling convention, but I'm not sure if @johnwickerson has covered that yet.

**Comment by Cathy-DYX** [comment]
Thank you so much!

**Comment by johnwickerson** [comment]
That’s right, it’s Lecture 10.
