### ISSUE TITLE
qemu-mips

### ISSUE THREAD

**Issue by sv720** [LangProc/langproc-2021-cw#11]
Hi, I was wondering what version/setup of qemu-mips will be used to test our compiler and where we can download it? qemu-system-mips is on apt but not sure if this is the same thing...
Would it also be possible to get a quick explanation as to how we can test the mips code that we generate (in a similar way to what was done in lab3) ?

**Comment by ymherklotz** [comment]
Hi, it should already be available in the vm, which installs packages: `qemu` and `qemu-user`.  This should be enough to get it working.

And to test the mips code that you generate, you should be able to follow the [instructions in the README](https://github.com/LangProc/langproc-2021-cw/blob/master/c_compiler.md#output-format).

**Comment by sv720** [comment]
Due to... challenges... in disk size - I'm not using a VM so I'm not using the Vagrant file (not yet at least).
I assume running this should work? 
      # MIPS cross-compiler stuff
      sudo apt-get -y install g++-mips-linux-gnu gdb-multiarch

      # QEMU run-time emulator
      sudo apt-get -y install qemu
