### ISSUE TITLE
MIPS Conversion

### ISSUE THREAD

**Issue by Aeroking21** [LangProc/langproc-2021-cw#14]
Hi,
I was looking at the MIPS conversion in Godbolt and noticed that with arithmetic expressions like the attached example, the compiler appears to evaluate the expression before it is put into MIPS (i.e the expression 2+2 is loaded in as 4 in line 5).

<img width="1136" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/55886814/157837304-a1502110-59da-4aa6-9c0e-82be7147664f.png">

I was under the assumption that everything would have to be directly converted to MIPS but the compiler seems evaluate arithmetic expressions before conversion? I am not quite sure why it does that, is it an optimization?

**Comment by ymherklotz** [comment]
It is an optimisation and not necessary, but it's quite an easy one to do.  This one is called constant folding, and a more powerful similar optimisation is constant propagation.

**Comment by Aeroking21** [comment]
Is there any way to get an unoptimized version of MIPS compiled from C to use just as reference for our test cases?

**Comment by ymherklotz** [comment]
It might not actually be possible to turn it off (It might be done implicitly during AST generation).

Instead, you could look at code like the following, and just translate the argument loading from the stack into `li` instructions for your constant case:

```c
int f(int a, int b) {
    return a + b;
}
```

**Comment by Aeroking21** [comment]
If I just wanted to convert a simple C file to MIPS1 just for my understanding are there any gcc tools to do that?

**Comment by ymherklotz** [comment]
I think godbolt does a good job for that, it even highlights lines that got translated so you can trace it back to the origin.  It should be quite simple to ignore tiny optimisations that slip through like constant folding.
