### ISSUE TITLE
Vagrant has stopped working.

### ISSUE THREAD

**Issue by AngeloA01** [LangProc/langproc-2021-cw#18]
Hello, 

When I try to vagrant up I have a strange error:

```Vagrant failed to initialize at a very early stage:

The "metadata.json" file for the box 'ubuntu/focal64' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:
https://www.vagrantup.com/docs/boxes/format.html
```
Unsure of how to proceed. Please advise. 
I am using MacOS.

Thanks.

**Comment by ymherklotz** [comment]
Hmm, have you tried doing:

```
vagrant destroy
vagrant up
```

**Comment by AngeloA01** [comment]
for ```vagrant destroy``` I get the same error message.

**Comment by AngeloA01** [comment]
Issue resolved, downloaded the box again from this webpage:

https://app.vagrantup.com/ubuntu/boxes/focal64/versions/20220311.0.0 
(Added in case someone has a similar issue.)

**Comment by johnwickerson** [comment]
Thanks very much for including the details about how you resolved your issue, for the benefit of others who might have the same problem.
