### ISSUE TITLE
Trying to link generated object

### ISSUE THREAD

**Issue by Gandinator123** [LangProc/langproc-2021-cw#21]
Hi, 

I am getting this error when trying to run the following command: 

![image](https://user-images.githubusercontent.com/65455744/158077749-9f61fac3-7578-4f5c-af6c-bfc55824c32b.png)

Is this because there is something wrong on our side or something wrong with the driver code?

Thanks!

**Comment by Gandinator123** [comment]
I am trying to compile default/test_RETURN.c and we generate the following code:

![image](https://user-images.githubusercontent.com/65455744/158078048-bee6c265-7be7-4e4d-8397-6486236b4a3d.png)

**Comment by ymherklotz** [comment]
Hi, could you post the whole minimal working example as text, including the assembly you generate and all the commands you input so that it is easier to reproduce.

I'm guessing you are maybe missing a `.globl f` directive.

**Comment by Gandinator123** [comment]
Hi, Yes. it was the .globl f that we missed in generating the function! Thanks.
