### ISSUE TITLE
Stack Frame

### ISSUE THREAD

**Issue by Aeroking21** [LangProc/langproc-2021-cw#23]
Hi,

How do we determine the stack frame size needed for a function so we can change the stack pointer?

How does the compiler know to allocate 24bytes for the `main` function here:

![Screen Shot 2022-03-16 at 09 22 33](https://user-images.githubusercontent.com/55886814/158558216-0d8a5af6-d25c-4632-b4c6-a1edaf50d432.png)

**Comment by ymherklotz** [comment]
As long as you allocate at least as much space as you'll use, that should be fine.  In this case it seems like GCC allocated a bit too much space than technically necessary (but it probably has some kind of performance reason like keeping addresses aligned).

In general though, most allocations will just be static, so you can just count how many free spaces you will need in the stack, and then allocate that much.  You then need to keep extra space if you want to call functions for example, or save registers if that's necessary.

**Comment by Aeroking21** [comment]
I'm not quite sure by what you mean by "just count how many free spaces you will need in the stack", how do I go about counting the free spaces?

**Comment by ymherklotz** [comment]
When you generate the mips assembly, you will have to place static `sw` instructions in a lot of places (in the example you show, addresses `20($sp)` and `8($fp)` are both used and are both static).  So, looking at that example, we had to store two variables on the stack `$2` and `$sp`, so we would need to decrement `$sp` by `8` at least, however, in this case it's decremented by `24`.  This can be done by walking through your whole AST, and counting how many variables you'll need to store, and allocate enough stack space for all of them.

**Comment by Aeroking21** [comment]
thanks, and I was unsure about what type of data structure we should use to implement the "program stack"?
