### ISSUE TITLE
When to use pointers in the yacc file

### ISSUE THREAD

**Issue by ptar124** [LangProc/langproc-2021-cw#25]
In lab 2, pointers are used to make new variables. what other situations are there in the coursework might we need to do the same?
![image](https://user-images.githubusercontent.com/22909681/159024917-7ae79d77-3999-4419-a684-360525175672.png)

**Comment by petraratkai** [comment]
You don't need to use pointers in the parser. You can either return a dynamically allocated variable (so using `new`), or you need to copy the objects. Copying the objects is just much less efficient, but it should be fine to use either, as long as all your types are correct. (If your AST consists of pointers, then your parser should also return pointers)
