### ISSUE TITLE
‘YYSTYPE::YYSTYPE()’ is implicitly deleted because the default definition would be ill-formed

### ISSUE THREAD

**Issue by harshil-shah9900** [LangProc/langproc-2021-cw#26]
Unable to solve this error after scouring the parser and lexer.
![image](https://user-images.githubusercontent.com/93000876/159129717-91e45fdb-6d6c-425a-9336-90065e64aa3e.png)

**Comment by ymherklotz** [comment]
Could you post the whole log of running `make clean && make -B`?

**Comment by harshil-shah9900** [comment]
[log.txt](https://github.com/LangProc/langproc-2021-cw/files/8311200/log.txt)

Attached is the log

Here is the makefile just in case:

CPPFLAGS += -std=c++11 -W -Wall -g -Wno-unused-parameter
CPPFLAGS += -I include

all : bin/c_compiler

src/parser.tab.cpp src/parser.tab.hpp : src/parser.y
	bison -v -d src/parser.y -o src/parser.tab.cpp

src/lexer.yy.cpp : src/lexer.flex src/parser.tab.hpp
	flex -o src/lexer.yy.cpp  src/lexer.flex

bin/c_compiler : src/c_compiler.o src/lexer.yy.o src/parser.tab.o
	mkdir -p bin
	g++ $(CPPFLAGS) -o bin/c_compiler $^
	

clean :
	rm -rf bin/*
	rm -f src/*.tab.cpp
	rm -f src/*.yy.cpp
	rm -f src/*.output
	rm -f src/*.tab.hpp
	rm -f src/*.o

**Comment by ymherklotz** [comment]
I'm quite sure it's a similar error as here: https://stackoverflow.com/questions/65466135/cant-use-string-val-in-union-flex-bison

Basically, `std::vector<node_ptr>` does not have a default constructor and default destructor, and so it cannot be used in a union.  The best solution to this would be to create a wrapper class around `std::vector<node_ptr>` with those classes defined.  This should allow you to fix those errors.

**Comment by harshil-shah9900** [comment]
That seems to have worked, thank you very much.
