### ISSUE TITLE
Assembly warning 

### ISSUE THREAD

**Issue by J-u1i0** [LangProc/langproc-2021-cw#30]
Assembler messages:
Warning: no .cprestore pseudo-op used in PIC code

Every time I make a function call the warning above is raised but the testcases pass.
I looked into it and read that it has to do with the $gp not being restored but I never designate a value to the $gp.
I am not sure how to use .cprestore, but have seen the driver code uses .cprestore when it uses $gp.

Do I need to resolve this warning?
If so how may I do it?

**Comment by ymherklotz** [comment]
If you do never change `$gp`, then it should be fine.  But I think it also doesn't hurt to add `.cprestore` just how GCC adds it.  I don't think it makes too much of a difference though.

**Comment by J-u1i0** [comment]
Ok, will do.
Thank you for your insight.
