### ISSUE TITLE
floating point arguments

### ISSUE THREAD

**Issue by Gandinator123** [LangProc/langproc-2021-cw#31]
Hi, 

we are unsure what the logic for the floating point arguments is. In godbolt we input this:

![image](https://user-images.githubusercontent.com/65455744/159740614-4aff6e9a-cb24-4f67-8725-06e5cb84324c.png)

However, if we do this:

![image](https://user-images.githubusercontent.com/65455744/159740813-dd0b218a-8846-479a-9649-c68e0aa1ace0.png)

The MIPS instruction changes even when there are still floats as arguments? Could we get some help please?

Thanks

**Comment by ymherklotz** [comment]
> The MIPS instruction changes even when there are still floats as arguments?

I'm not quite sure what you mean by that.  Do you mean that it looks like code that just has `int`?

This is obeying the MIPS calling convention, which can be [checked in the MIPS ABI](http://math-atlas.sourceforge.net/devel/assembly/mipsabi32.pdf#page=29), in figure 3-22.  You can check out:

> n1, s1, n2, s2 | $4, $5, $6, $7

This says that: `f(int, float, int, float)` will be passed through registers `$4, $5, $6, $7`, so the floats are passed through the int registers.

On the other hand:

> s1, n1, s2, n2 | $f12, $5, $6, $7

Says that `f(float, int, float, int)` is passed on `$f12, $5, $6, $7`.  So the first floats are passed on float registers, but if you have an int, the rest of the arguments are also passed on the int registers, even if they are floats.

**Comment by Gandinator123** [comment]
thanks!
