### ISSUE TITLE
Register values

### ISSUE THREAD

**Issue by Aeroking21** [LangProc/langproc-2021-cw#32]
Hi,

For an input C function such as below, which doesn't explicitly return a value.

```
int main() {
    int x = 32;
}
```
In our compiler do we have to store a 0 in $2 as an implicit return value as the function doesn't return anything?

**Comment by ymherklotz** [comment]
Yes, if a function doesn't return anything (which I think is only valid in the `main` function), then your compiler should put 0 into `$2` before returning.

**Comment by Aeroking21** [comment]
Thanks, I also had a question regarding the compilation and testing of our compiler.

Right now I am attempting to manually test this test case [link](https://github.com/LangProc/langproc-2021-cw/blob/master/compiler_tests/default/test_RETURN.c), and I am following the instruction in `c_compiler.md`. However when running  `mips-linux-gnu-gcc -mfp32 -static -o test_program test_program.o test_program_driver.c`.

I keep on getting the following error and I am not sure what is going wrong:

```
usr/lib/gcc-cross/mips-linux-gnu/9/../../../../mips-linux-gnu/bin/ld: /tmp/ccJxjMQU.o: in function `main':
test_RETURN_driver.c:(.text+0x1c): undefined reference to `f'
/usr/lib/gcc-cross/mips-linux-gnu/9/../../../../mips-linux-gnu/bin/ld: test_RETURN_driver.c:(.text+0x24): undefined reference to `f'
collect2: error: ld returned 1 exit status
```

This is the output from our compiler:
```
f:
addiu $sp, $sp, -16
sw $fp, 12($sp)
move $fp, $sp
li $2, 10
b $ENDOFMAIN_0
$ENDOFMAIN_0:
move $sp, $fp
lw $fp, 12($sp)
addiu $sp, $sp, 16
j $31
```

**Comment by Aeroking21** [comment]
I think I just saw from another closed comment that we might seem to be missing the `.globl f` directive, what is the need for this directive and would it be required for the main function?

**Comment by ymherklotz** [comment]
It is indeed that `.globl f` is missing, and this directive is needed for all functions so that the linker exposes them to other translation units.
