### ISSUE TITLE
Coursework Submission (Commit Hash)

### ISSUE THREAD

**Issue by dereklai1** [LangProc/langproc-2021-cw#33]
> Submission will be via GitHub (code) and Teams (commit hash)

Just a quick question about where to submit the repo hash to. I looked around in the teams channel and couldn't find any document for the submission.

**Comment by ymherklotz** [comment]
Maybe @johnwickerson can clarify this.  I believe he will create a document to submit them too like with the labs.

**Comment by johnwickerson** [comment]
Yep, spreadsheet now live, pairings.xlsx in the Files tab on Teams.
