### ISSUE TITLE
Bison Gets Stuck (infinite loop?)

### ISSUE THREAD

**Issue by paul-vangerow** [LangProc/langproc-2021-cw#7]
So we wanted to test our lexer/parser, but when we run it it gets stuck (likely an infinite loop). We tried the debug mode, and that parses everything correctly, though never results in a ROOT node.

Is there any way to check whats happening during run-time or some other way to find causes of infinite loops?

**Comment by ymherklotz** [comment]
What do you mean stuck in a loop? Did you try giving it the end of file signal `CTRL-D` when running on the command line?

**Comment by paul-vangerow** [comment]
I mean that when we run it, first we build everything which works fine, then I run the command

./parser_name input_file.c >> output_file.txt

And this command never finishes executing and we have to quit with CTRL_C

**Comment by ymherklotz** [comment]
So does that mean you are setting `yyin` manually in your `main` function to pass the `input_file.c` to bison?  I think the following might fix it if you are not changing `yyin` anywhere:

```bash
./parser_name <input_file.c >output_file.txt
```

**Comment by paul-vangerow** [comment]
Yup that was the issue, I wasn't inputting the c file properly. Thanks a lot!
